# Generated by Django 4.2.5 on 2023-12-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autoshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название авто')),
                ('type', models.CharField(max_length=20, verbose_name='Тип авто')),
                ('availability', models.BooleanField(verbose_name='Наличие')),
                ('range', models.CharField(max_length=20, verbose_name='Пробег')),
                ('engine', models.CharField(max_length=20, verbose_name='Тип двигателя')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Год производства')),
                ('image', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
